spring.application.name=Service-emprunteur
server.port=8082

# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotheque_emprunteur?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Personnaliser le chemin d'accès (optionnel)
springdoc.swagger-ui.path=/swagger-ui.html
# Trier les endpoints par méthode HTTP (GET, POST, etc.)
springdoc.swagger-ui.operationsSorter=method